define(['handlers/product/list-handler',
        'handlers/product/view-handler',
        'handlers/product/create-handler',
        'handlers/product/update-handler',
        'handlers/category/list-handler',
        'handlers/category/view-handler',
        'handlers/category/create-handler',
        'handlers/category/update-handler',
        'handlers/supplier/supplier-handler',
        'handlers/order/order-handler'], function (
        productListHandler,
        productViewHandler,
        productCreateHandler,
        productUpdateHandler,
        categoryListHandler,
        categoryViewHandler,
        categoryCreateHandler,
        categoryUpdateHandler,
        supplierHandler,
        orderHandler) {
            return [
                { name: 'default-route', route: '/', handler: productListHandler },
                { name: 'list-product', route: '/product', handler: productListHandler },
                { name: 'view-product', route: '/product/view/:id', handler: productViewHandler },
                { name: 'create-product', route: '/product/create', handler: productCreateHandler },
                { name: 'update-product', route: '/product/update/:id', handler: productUpdateHandler },
                { name: 'list-category', route: '/category', handler: categoryListHandler },
                { name: 'view-category', route: '/category/view/:id', handler: categoryViewHandler },
                { name: 'create-category', route: '/category/create', handler: categoryCreateHandler },
                { name: 'update-category', route: '/category/update/:id', handler: categoryUpdateHandler },
                { name: 'list-supplier', route: '/supplier', handler: supplierHandler('list') },
                { name: 'view-supplier', route: '/supplier/view/:id', handler: supplierHandler('view') },
                { name: 'create-supplier', route: '/supplier/create', handler: supplierHandler('create') },
                { name: 'update-supplier', route: '/supplier/update/:id', handler: supplierHandler('update') },
                { name: 'list-order', route: '/order', handler: orderHandler.handle('list') },
                { name: 'view-order', route: '/order/view/:id', handler: orderHandler.handle('view') },
                { name: 'create-order', route: '/order/create', handler: orderHandler.handle('create') },
                { name: 'update-order', route: '/order/update/:id', handler: orderHandler.handle('update') }
            ];
        });
